In [42]:
import numpy as np

class Graph:
    def __init__(self,vertices):
        self.vertices=vertices
        self.Mat=np.zeros((vertices,vertices))
        
    def insert_edge(self,u,v,w=1):
        self.Mat[u][v]=w
    
    def remove_edge(self,u,v):
        if self.Mat[u][v]==0:
            print('edge not present')
        else:
            self.Mat[u][v]=0
    
    def exist_edge(self,u,v):
        return self.Mat[u][v]!=0
    
    def vertex_count(self):
        return self.vertices
    
    def edge_count(self):
        count=0
        for i in range(self.vertices):
            for j in range(self.vertices):
                if self.Mat[i][j]!=0:
                    count+=1
        return count
    
    def vertices(self):
        for i in range(self._vertices):
            print(i,end=' ')
        print()
    
    def edges(self):
        for i in range(self.vertices):
            for j in range(self.vertices):
                if self.Mat[i][j]!=0:
                    print(i,'--',j)
        print()
    
    def indegree(self,v):
        count=0
        for i in range(self.vertices):
            if self.Mat[i][v]!=0:
                count+=1
        return count
    
    def outdegree(self,v):
        count=0
        for j in range(self.vertices):
            if self.Mat[v][j]!=0:
                count+=1
        return count
    
    def display(self):
        print(self.Mat)

# undirected graph implementation
<img src='un.png'>

In [7]:

g=Graph(4)
g.display()
print('vertices',g.vertex_count())
print('edges',g.edge_count())


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
vertices 4
edges 0


In [8]:
g.insert_edge(0,1)
g.insert_edge(0,2)
g.insert_edge(1,2)
g.insert_edge(2,3)

g.insert_edge(1,0)
g.insert_edge(2,0)
g.insert_edge(2,1)
g.insert_edge(3,2)

g.display()
print('vertices',g.vertex_count())
print('edges',g.edge_count())

[[0. 1. 1. 0.]
 [1. 0. 1. 0.]
 [1. 1. 0. 1.]
 [0. 0. 1. 0.]]
vertices 4
edges 8


In [9]:
g.edges()

0 -- 1
0 -- 2
1 -- 0
1 -- 2
2 -- 0
2 -- 1
2 -- 3
3 -- 2



In [10]:
g.exist_edge(1,3)

False

In [11]:
g.exist_edge(2,0)

True

In [12]:
g.indegree(2)

3

In [13]:
g.remove_edge(1,2)

In [14]:
g.exist_edge(1,2)

False

# weighted undirected graph
<img src='wun.png'>

In [18]:
w=Graph(4)
w.display()
print('vertices',w.vertex_count())
print('edges',w.edge_count())

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
vertices 4
edges 0


In [19]:
w.insert_edge(0,1,26)
w.insert_edge(0,2,16)
w.insert_edge(1,2,12)
w.insert_edge(2,3,8)

w.insert_edge(1,0,26)
w.insert_edge(2,0,16)
w.insert_edge(2,1,12)
w.insert_edge(3,2,8)

In [20]:
w.display()
print('vertices',w.vertex_count())
print('edges',w.edge_count())

[[ 0. 26. 16.  0.]
 [26.  0. 12.  0.]
 [16. 12.  0.  8.]
 [ 0.  0.  8.  0.]]
vertices 4
edges 8


In [21]:
w.edges()

0 -- 1
0 -- 2
1 -- 0
1 -- 2
2 -- 0
2 -- 1
2 -- 3
3 -- 2



In [22]:
w.exist_edge(1,3)

False

In [23]:
w.exist_edge(2,0)

True

In [25]:
w.indegree(2)

3

# Directed graph implementation
<img src='di.png'>

In [43]:
g=Graph(4)
g.display()
print('vertices',g.vertex_count())
print('edges',g.edge_count())

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
vertices 4
edges 0


In [44]:
g.insert_edge(0,1)
g.insert_edge(0,2)
g.insert_edge(1,2)
g.insert_edge(2,3)


In [45]:
g.display()
print('vertices',g.vertex_count())
print('edges',g.edge_count())

[[0. 1. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
vertices 4
edges 4


In [46]:
g.edges()

0 -- 1
0 -- 2
1 -- 2
2 -- 3



In [47]:
g.exist_edge(3,2)

False

In [48]:
g.exist_edge(2,3)

True

In [49]:
g.remove_edge(3,2)

edge not present


In [50]:
g.edges()

0 -- 1
0 -- 2
1 -- 2
2 -- 3



# weighted Directed Graph
<img src='wdi.png'>

In [51]:
g=Graph(4)
g.display()
print('vertices',g.vertex_count())
print('edges',g.edge_count())

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
vertices 4
edges 0


In [52]:
g.insert_edge(0,1,26)
g.insert_edge(0,2,16)
g.insert_edge(1,2,12)
g.insert_edge(2,3,8)

In [53]:
g.display()
print('vertices',g.vertex_count())
print('edges',g.edge_count())

[[ 0. 26. 16.  0.]
 [ 0.  0. 12.  0.]
 [ 0.  0.  0.  8.]
 [ 0.  0.  0.  0.]]
vertices 4
edges 4


In [54]:
g.edges()

0 -- 1
0 -- 2
1 -- 2
2 -- 3



In [55]:
g.indegree(2)

2

In [56]:
g.outdegree(2)

1